In [2]:
import pandas as pd

# create (and access) a dictionary containing different types of data (lists, strings, dictionaries)

In [7]:
# let's first create a list
my_list = [1,2,3,5,7,8]

# let's also create a string
my_str = "Hello world, how are you"

# and a dictionary
my_dict = {'a': 34, 'b': 36}

# and an dummy dataframe
my_df = pd.DataFrame({'a':[1,2,4,5,10],
                      'b':[9,5,3,5,3],
                     }
                    )

# we can put all of these in a dictionary!

my_super_dct = {'list': my_list,
               'string': my_str,
               'dict': my_dict,
               'df': my_df,
               }

In [8]:
# let's look at the dict
my_super_dct

{'list': [1, 2, 3, 5, 7, 8],
 'string': 'Hello world, how are you',
 'dict': {'a': 34, 'b': 36},
 'df':     a  b
 0   1  9
 1   2  5
 2   4  3
 3   5  5
 4  10  3}

# create a dictionary from two lists (using zip)

In [14]:
first_list = ['a', 'b', 'c', 'd']
second_list = [1, 2, 3,4]

my_dict = {}

for f,s in zip(first_list, second_list):
    my_empty_dict[f] = s

In [15]:
my_empty_dict

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

# create a dictionary using a dictionary comprehension

In [17]:
first_list = ['a', 'b', 'c', 'd']
second_list = [1,2,3,4]

my_dict = {f:s for f,s in zip(first_list, second_list)}

In [18]:
my_dict

{'a': 1, 'b': 2, 'c': 3, 'd': 4}

# discuss when you would use a dict and when a list

* list:
    * when we need to store values that we want to iterate over
    * that we want to address (with indexing e.g.)
    * we want to have access to information about that list (length, maximum, minimum, average, etc.)
    * the elements are not in need of a key / description. That means, we don't primarily care for retrieving the elements out of this list (althoug it is possible) 
    
* dictionary
    * when we need to store something that we want to iterate over
    * that we want to address but with exact "keys"
    * when we need to have **structured data** (key-value-pairs)
        * e.g. you want to store the score of your 5 machine learning models that you have trained. key: name of the model, value: the score itself
    * structured data, that we need to retrieve at some point, by providing the key and getting the value
    * with regards what we do now: JSON, relational databases (because they need nested dictionaries)

# read a dict into a dataframe

In [21]:
# first build it with a list comprehension (see above)
first_list = ['a', 'b', 'c', 'd']
second_list = [1,2,3,4]

my_dict = {f:s for f,s in zip(first_list, second_list)}

# put it in a dataframe. Caution: Must pass an index (demonstrate without passing index first)
#I'm just passing here the numbers 0, 1,2,3 as index

pd.DataFrame(my_dict, index=range(len(my_dict)))

   a  b  c  d
0  1  2  3  4
1  1  2  3  4
2  1  2  3  4
3  1  2  3  4

In [22]:
# or in one line
pd.DataFrame({'a':[23,23,6,723,4,1],
              'b':[2,2,4,7,2,4],
             })

     a  b
0   23  2
1   23  2
2    6  4
3  723  7
4    4  2
5    1  4

In [23]:
my_dict

KeyError: 0

In [24]:
pwd

'/home/flo/Documents/coding/ironhack_ta/data_ber_2021_01/workshops'